MusicHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),
    path('account/', include('account.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    
    path('main/', main_page, name = 'main'),
    path('uploadmusic/', upload_music, name = 'upload-music' ),
    path('home/', ListMusicView.as_view(), name = 'home'),
    path('delete/<int:pk>/', DeleteMusicView.as_view(), name = 'delete'),
    path('create_album/', create_album, name = 'create-album'),
    path('home/albums/', AlbumMusicView.as_view() , name = 'album-list'),
    path('home/albums/detail/<int:pk>/', AlbumDetailView, name = 'album-detail'),
    path('delete/album/<int:pk>/', DeleteAlbumView.as_view(), name = 'delete-album'),
    path('create_playlist/', create_playlist, name = 'create-playlist'),
    path('home/playlist/', PlayListView.as_view() , name = 'playlist'),
    path('home/playlist/detail/<int:pk>/', PlayListDetailView, name = 'playlist-detail'),
    path('delete/playlist/<int:pk>/', DeletePlayListView.as_view(), name = 'delete-playlist'),
]

music/models.py
from django.db import models
from django.contrib.auth.models import User

class AlbumModel(models.Model):
    name = models.CharField(max_length = 25)
    author = models.ForeignKey(User, on_delete = models.CASCADE, null = True)

    def __str__(self):
        return self.name

class MusicModel(models.Model):
    title = models.CharField(max_length=20)
    file = models.FileField(upload_to='music_file/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(null = True, auto_now_add = True)
    album = models.ForeignKey(AlbumModel, on_delete = models.CASCADE, null = True, blank = True)

    class Meta:
        ordering = ['-publication_date']

    def __str__(self):
        return self.title
    

class PlayListModel(models.Model):
    title = models.CharField(max_length=25)
    songs = models.ManyToManyField(MusicModel)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.title

music/forms.py
from django import forms
from .models import MusicModel, AlbumModel, PlayListModel



class MusicForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['album'].queryset = AlbumModel.objects.filter(author=user)

   

    class Meta:
        model = MusicModel
        fields = ['title', 'file', 'album']

class AlbumForm(forms.ModelForm):
    class Meta:
        model = AlbumModel
        fields = ['name']


class PlayListForm(forms.ModelForm):
    songs = forms.ModelMultipleChoiceField(
        queryset=MusicModel.objects.all(),
        widget=forms.SelectMultiple,
        required=True,
    )

    class Meta:
        model = PlayListModel
        fields = ['title', 'songs']    
    



    

music/views.py
import os
from django.http import FileResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, DetailView
from .forms import *
from .permissions import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator



def main_page(request):
    return render(request, 'music/main_page.html')



def upload_music(request):
    if request.method == 'POST':
        form = MusicForm(request.user, request.POST, request.FILES)
        file = request.FILES.get('file')
        if form.is_valid() and file.name.endswith(('.mp3', '.wav', '.flac')):
            form = form.save(commit=False)
            form.author = request.user 
            form.save()
            return redirect('home')
    else:
        form = MusicForm(request.user)
    
    return render(request, 'music/upload_music.html', {'form': form})

class ListMusicView(LoginRequiredMixin, ListView):
    paginate_by = 4
    model = MusicModel
    template_name = 'music/home_page.html'

   

class DeleteMusicView(AuthorPermissionsMixin,DeleteView):
    model = MusicModel
    success_url = reverse_lazy('home')



def create_album(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            return redirect('album-list')
    else:
        form = AlbumForm()
        
    return render(request, 'music/create_album.html', {'form': form})


class AlbumMusicView(ListView):
    paginate_by = 4
    model = AlbumModel
    template_name = 'music/album_page.html'

def AlbumDetailView(request, pk):
    albums = AlbumModel.objects.filter(id = pk)
    music = MusicModel.objects.all()

    return render(request, 'music/album_detail.html', {'music': music, 'albums': albums})


class DeleteAlbumView(AuthorPermissionsMixin,DeleteView):
    model = AlbumModel
    success_url = reverse_lazy('home')



def create_playlist(request):
    if request.method == 'POST':
        form = PlayListForm(request.POST)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.author = request.user
            playlist.save()
            form.save_m2m()
            return redirect('playlist')
    else:
        form = PlayListForm()
        
    return render(request, 'music/create_playlist.html', {'form': form})


class PlayListView(ListView):
    
    model = PlayListModel
    template_name = 'music/playlist_page.html'


def PlayListDetailView(request, pk):
    playlist = PlayListModel.objects.get(id = pk)
    music = playlist.songs.all()

    return render(request, 'music/playlist_detail.html', {'music': music, 'playlist': playlist})


class DeletePlayListView(AuthorPermissionsMixin,DeleteView):
    model = PlayListModel
    success_url = reverse_lazy('playlist')

music/templates/music/album_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MusicHub{% endblock%}
	
{% block content %}
{% if request.user.is_authenticated %}
		<div class="main home-main">
			<div class="home_title_block">
				<h2 class="main__title hometitle">MusicHub</h2>
				<a class="home_user" href="{% url 'detail' user.id %}">{{ request.user }}</a>
			</div>

			
      <div class="back-to-home_block album-detail-back">
            <a class="back-to-home" href="{% url 'home' %}">Обратно на главную</a>
        </div>
      <div class="title_album-block">  
				<h2 class="title_album">{{ albums.0.name }}</h2>
			</div>
      {% for mus in music %}
      {% if mus.album in albums %}
			<div class="home_block_music">
				<div class="home_music_title_author">
					<a class = 'home_music_author' href="{% url 'detail' mus.author.id %}">{{ mus.author }}</a> - {{ mus.title }} {% if mus.album %}<a href="{% url 'album-detail' mus.album.id %}" class="home_music_album">({{mus.album}})</a>{% endif %}
				
				</div>
				{% if request.user == mus.author %}
					<div class="home_music_delete_block">
						<a class = 'home_music_delete' href="{% url 'delete' mus.id %}">Удалить</a>
					</div>
				{% endif %}
				<div class="home_music_file">
					<audio controls = "controls" class = 'music_player'>
  					<source src="{{ mus.file.url }}" >
					</audio>
				</div>
				<div class="home_music_date">
					{{mus.publication_date.date}}
				</div>
			</div>
      
      {% endif %}
			{% endfor %}
      

      
    
			
			<img src="{% static 'img/logo.jpg' %}" alt="" class="main_page_image" />
			<h2 class="main_page_suptitle">MusicHub</h2>
			
		</div>
		{% endif %}
{% endblock %}

music/templates/music/album_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MusicHub{% endblock%}
	
{% block content %}
{% if request.user.is_authenticated %}
		<div class="main home-main">
			<div class="home_title_block">
				<h2 class="main__title hometitle">MusicHub</h2>
				<a class="home_user" href="{% url 'detail' user.id %}">{{ request.user }}</a>
			</div>
			
      <div class="music-album">
				<ul>
					<li class = 'switch_to_music'><a class = 'sw_to_music' href="{% url 'home' %}">Музыка</a></li>
					<li class = 'switch_to_album'><a class = 'sw_to_album' href="{% url 'album-list' %}">Альбомы</a></li>
					<li class = 'switch_to_playlist'><a class = 'sw_to_playlist' href="{% url 'playlist' %}">Ваши плейлисты</a></li>
				</ul>
			</div>


			<div class="upload_music">
				<a class = 'upl_music' href="{% url 'upload-music' %}">Добавить песню</a>
			</div>

			<div class="create_album">
				<a class = 'cr_album' href="{% url 'create-album' %}">Добавить альбом</a>
			</div>

			<div class="create_playlist">
				<a class = 'cr_playlist' href="{% url 'create-playlist' %}">Добавить плейлист</a>
			</div>

			{% for album in albummodel_list %} 
			<div class="home_block_music album_block">
				<div class="home_music_title_author album_title_author">
					<a class = 'home_music_author' href="{% url 'detail' album.author.id %}">{{ album.author }}</a> - <a class = 'album_name' href="{% url 'album-detail' album.id %}">{{ album.name }}</a>
				
				</div>

        {% if request.user == album.author %}
					<div class="home_music_delete_block album-delete-block">
						<a class = 'home_music_delete album-delete' href="{% url 'delete-album' album.id %}">Удалить</a>
					</div>
				{% endif %}
				
				<div class="home_music_date">
					{{music.publication_date.date}}
				</div>
			</div>
			{% endfor %}
			<img src="{% static 'img/logo.jpg' %}" alt="" class="main_page_image" />
			<h2 class="main_page_suptitle">MusicHub</h2>
			<div class="pagination_block">
				
				<ul>
        {% for p in paginator.page_range %}
						{% if page_obj.has_other_pages %}
            {% if page_obj.number == p %}
                <li class="pagionation_selected">{{ p }}</li>
            

            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
                <li class = 'pagionation_no_selected'>
                    <a class = 'pag_no_selected ' href="?page={{p}}">{{ p }}</a>
                </li>
                
            {% endif %}
						{% endif %}
        {% endfor %}
    		</ul>
			</div>
		</div>
		{% endif %}
{% endblock %}

music/templates/music/albummodel_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Удаление {% endblock %}

{% block content %}
<div class="main">
    <div class="main__block">
      <form action="" method="post">
        {% csrf_token %}
        <h1 class="delete_title">Вы уверены, что хотите удалить?</h1>
        <button class = 'main__button' type="submit">Удалить</button>
      </form>
    </div>
</div>
   
{% endblock %}

music/templates/music/create_album.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Добавление альбома{% endblock %}


{% block content %}
{% if request.user.is_authenticated %}
<div class="main">
    <div class="main__block">
        <h2 class="main__title">Добавить альбом</h2>
            <form action="" method="post">
                {% csrf_token %}
                <div>
                    {{form.name|add_class:'default_form'|attr:'placeholder:Название альбома'}}
                </div>

                
                <div>
                    <button type="submit" class="main__button">Добавить</button>
                </div>
            </form>
    </div>
</div>
{% endif %}
{% endblock %}

music/templates/music/create_playlist.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Добавление плейлиста{% endblock %}


{% block content %}
{% if request.user.is_authenticated %}
<script src="{% static 'django_select2/js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'django_select2/js/select2.full.js' %}"></script>
<script src="{% static 'django_select2/js/i18n/ru.js' %}"></script>
<div class="main">
    <div class="main__block">
        <h2 enctype="multipart/form-data" class="main__title">Добавить плейлист</h2>
            <form action="" method="post">
                {% csrf_token %}
                <div>
                    {{form.title|add_class:'default_form'|attr:'placeholder:Название плейлиста'}}
                </div>
                
                <div>
                    
                    {{form.songs|add_class:'default_form playlist_form'}}
                </div>
               
                
                <div>
                    <button type="submit" class="main__button">Добавить</button>
                </div>
            </form>
    </div>
</div>
{% endif %}
{% endblock %}

music/templates/music/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MusicHub{% endblock%}
	
{% block content %}
{% if request.user.is_authenticated %}
		<div class="main home-main">
			<div class="home_title_block">
				<h2 class="main__title hometitle">MusicHub</h2>
				<a class="home_user" href="{% url 'detail' user.id %}">{{ request.user }}</a>
			</div>

			<div class="music-album">
				<ul>
					<li class = 'switch_to_music'><a class = 'sw_to_music' href="{% url 'home' %}">Музыка</a></li>
					<li class = 'switch_to_album'><a class = 'sw_to_album' href="{% url 'album-list' %}">Альбомы</a></li>
					<li class = 'switch_to_playlist'><a class = 'sw_to_playlist' href="{% url 'playlist' %}">Ваши плейлисты</a></li>
				</ul>
			</div>


			<div class="upload_music">
				<a class = 'upl_music' href="{% url 'upload-music' %}">Добавить песню</a>
			</div>

			<div class="create_album">
				<a class = 'cr_album' href="{% url 'create-album' %}">Добавить альбом</a>
			</div>

			<div class="create_playlist">
				<a class = 'cr_playlist' href="{% url 'create-playlist' %}">Добавить плейлист</a>
			</div>

			{% for music in musicmodel_list %} 
			<div class="home_block_music">
				<div class="home_music_title_author">
					<a class = 'home_music_author' href="{% url 'detail' music.author.id %}">{{ music.author }}</a> - {{ music.title }} {% if music.album %}<a href="{% url 'album-detail' music.album.id %}" class="home_music_album">({{music.album}})</a>{% endif %}
				
				</div>
				{% if request.user == music.author %}
					<div class="home_music_delete_block">
						<a class = 'home_music_delete' href="{% url 'delete' music.id %}">Удалить</a>
					</div>
				{% endif %}
				<div class="home_music_file">
					<audio controls = "controls" class = 'music_player'>
  					<source src="{{ music.file.url }}" >
					</audio>
				</div>
				<div class="home_music_date">
					{{music.publication_date.date}}
				</div>
			</div>
			{% endfor %}
			
			<img src="{% static 'img/logo.jpg' %}" alt="" class="main_page_image" />
			<h2 class="main_page_suptitle">MusicHub</h2>
			<div class="pagination_block">
				
				<ul>
        {% for p in paginator.page_range %}
						{% if page_obj.has_other_pages %}
            {% if page_obj.number == p %}
                <li class="pagionation_selected">{{ p }}</li>
            

            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
                <li class = 'pagionation_no_selected'>
                    <a class = 'pag_no_selected ' href="?page={{p}}">{{ p }}</a>
                </li>
                
            {% endif %}
						{% endif %}
        {% endfor %}
    		</ul>
			</div>
		</div>
		{% endif %}
{% endblock %}

music/templates/music/main_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>MusicHub</title>
</head>
<body>
    <div class="main_page">
        <img src="{% static 'img/logo.jpg' %}" alt="" class="main_page_image">
        <h2 class="main_page_suptitle">MusicHub</h2>
        <h1 class="main_page_title">MusicHub</h1>
        <p class="subtitle">Присоединяйся к сообществу музыкантов</p>
        <div class="btn">
            <a class ='main_page_button' href="{% url 'register' %}">Регистрация</a>
            
    </div>
        
    </div>
</body>
</html>

music/templates/music/musicmodel_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Удаление {% endblock %}

{% block content %}
<div class="main">
    <div class="main__block">
      <form action="" method="post">
        {% csrf_token %}
        <h1 class="delete_title">Вы уверены, что хотите удалить?</h1>
        <button class = 'main__button' type="submit">Удалить</button>
      </form>
    </div>
</div>
   
{% endblock %}

music/templates/music/playlist_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MusicHub{% endblock%}
	
{% block content %}
{% if request.user.is_authenticated %}
		<div class="main home-main">
			<div class="home_title_block">
				<h2 class="main__title hometitle">MusicHub</h2>
				<a class="home_user" href="{% url 'detail' user.id %}">{{ request.user }}</a>
			</div>

			
      <div class="back-to-home_block album-detail-back">
            <a class="back-to-home" href="{% url 'home' %}">Обратно на главную</a>
        </div>
			{% if playlist.author == request.user %}
      <div class="title_album-block">  
				<h2 class="title_album">{{ playlist.title }}</h2>
			</div>
     
      {% for mus in music %}
      
			<div class="home_block_music">
				<div class="home_music_title_author">
					<a class = 'home_music_author' href="{% url 'detail' mus.author.id %}">{{ mus.author }}</a> - {{ mus.title }} {% if mus.album %}<a href="{% url 'album-detail' mus.album.id %}" class="home_music_album">({{mus.album}})</a>{% endif %}
				
				</div>
				
				<div class="home_music_file">
					<audio controls = "controls" class = 'music_player'>
  					<source src="{{ mus.file.url }}" >
					</audio>
				</div>
				<div class="home_music_date">
					{{mus.publication_date.date}}
				</div>
			</div>
      
      
			{% endfor %}
			{% endif %}
      <img src="{% static 'img/logo.jpg' %}" alt="" class="main_page_image" />
			<h2 class="main_page_suptitle">MusicHub</h2>
			<div class="pagination_block">
{% endif %}
{% endblock %}

music/templates/music/playlist_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MusicHub{% endblock%}
	
{% block content %}
{% if request.user.is_authenticated %}
		<div class="main home-main">
			<div class="home_title_block">
				<h2 class="main__title hometitle">MusicHub</h2>
				<a class="home_user" href="{% url 'detail' user.id %}">{{ request.user }}</a>
			</div>
			
      <div class="music-album">
				<ul>
					<li class = 'switch_to_music'><a class = 'sw_to_music' href="{% url 'home' %}">Музыка</a></li>
					<li class = 'switch_to_album'><a class = 'sw_to_album' href="{% url 'album-list' %}">Альбомы</a></li>
          <li class = 'switch_to_playlist'><a class = 'sw_to_playlist' href="{% url 'playlist' %}">Ваши плейлисты</a></li>
				</ul>
			</div>


			<div class="upload_music">
				<a class = 'upl_music' href="{% url 'upload-music' %}">Добавить песню</a>
			</div>

			<div class="create_album">
				<a class = 'cr_album' href="{% url 'create-album' %}">Добавить альбом</a>
			</div>

      <div class="create_playlist">
				<a class = 'cr_playlist' href="{% url 'create-playlist' %}">Добавить плейлист</a>
			</div>
      
			{% for playlist in playlistmodel_list %} 
      {% if playlist.author == request.user %}
			<div class="home_block_music album_block">
				<div class="home_music_title_author album_title_author">
					<a class = 'album_name' href="{% url 'playlist-detail' playlist.id %}">{{ playlist.title }}</a>
				
				</div>

        {% if request.user == playlist.author %}
					<div class="home_music_delete_block album-delete-block">
						<a class = 'home_music_delete album-delete' href="{% url 'delete-playlist' playlist.id %}">Удалить</a>
					</div>
				{% endif %}
				
			</div>
      {% endif %}
			{% endfor %}
			<img src="{% static 'img/logo.jpg' %}" alt="" class="main_page_image" />
			<h2 class="main_page_suptitle">MusicHub</h2>
			<div class="pagination_block">
				
				<ul>
        {% for p in paginator.page_range %}
						{% if page_obj.has_other_pages %}
            {% if page_obj.number == p %}
                <li class="pagionation_selected">{{ p }}</li>
            

            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
                <li class = 'pagionation_no_selected'>
                    <a class = 'pag_no_selected ' href="?page={{p}}">{{ p }}</a>
                </li>
                
            {% endif %}
						{% endif %}
        {% endfor %}
    		</ul>
			</div>
		</div>
		{% endif %}
{% endblock %}

music/templates/music/playlistmodel_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Удаление {% endblock %}

{% block content %}
<div class="main">
    <div class="main__block">
      <form action="" method="post">
        {% csrf_token %}
        <h1 class="delete_title">Вы уверены, что хотите удалить?</h1>
        <button class = 'main__button' type="submit">Удалить</button>
      </form>
    </div>
</div>
   
{% endblock %}

music/templates/music/upload_music.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Добавление песни{% endblock %}


{% block content %}
{% if request.user.is_authenticated %}
<div class="main">
    <div class="main__block">
        <h2 class="main__title">Добавить песню</h2>
            <form enctype="multipart/form-data" action="" method="post">
                {% csrf_token %}
                <div>
                    {{form.title|add_class:'default_form'|attr:'placeholder:Название песни'}}
                </div>

                <div>
                    <h3 class = 'album_title'>Альбом</h3>

                    {{form.album|add_class:'default_form'}}
                   
                </div>

               


                <div class="file-upload">
                    {{form.file|add_class:'file-input'|attr:'id:file'}}
                    <label for="file" class="file-label">Добавить файл</label>
                    
                </div>
                <div>
                    <button type="submit" class="main__button">Добавить</button>
                </div>
            </form>
    </div>
</div>
{% endif %}
{% endblock %}
<!--
<div class="input__wrapper">
    {{form.file|add_class:'input input__file'|attr:'id:input__file'}}
    <label for="input__file" class="file-label">Добавить файл</label>
    
</div>
-->